# Config parameters for router data construction:
api_key: ""
unified_qa_data_path: 'data/unified_qa_data.csv'
llm_description_path: 'configs/LLM_Descriptions.json'
llm_embedding_path: 'configs/llm_description_embedding.pkl'
saved_router_data_path: 'data/router_data.csv'
query_response_length: 512


# Config parameters for graph_router training:
seed: 1881
wandb_key: '84679e2187c9dff30d66ba819d630dc2f25a0237'
model_path: 'model_path/best_model.pth'
train_epoch: 1000
scenario: "Cost First"  # "Performance First", "Balance", and "Cost First"
llm_num: 10
learning_rate: 0.0003
weight_decay: 0.0001
train_mask_rate: 0.5
batch_size: 32
num_task: 4
split_ratio: [0.7, 0.1, 0.2]
embedding_dim: 8
edge_dim: 3